project: default
source:
  repoURL: 'https://github.com/bacherfl/keptn-analysis-demo'
  path: sample-app/chart
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: podtato-kubectl
syncPolicy:
  automated:
    prune: true
    selfHeal: true
