apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnApp
metadata:
  creationTimestamp: "2024-01-17T09:59:47Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: keptn
  name: podtato-head-2
  resourceVersion: "15776"
  uid: 69a04133-3db8-4f31-b990-98d6315dc27c
spec:
  revision: 1
  version: 95a0b0ddca
  workloads:
  - name: podtato-head-entry
    version: 0.1.0
  - name: podtato-head-hat
    version: 0.1.0
  - name: podtato-head-left-arm
    version: 0.1.0
  - name: podtato-head-left-leg
    version: 0.1.0
  - name: podtato-head-right-arm
    version: 0.1.0
  - name: podtato-head-right-leg
    version: 0.1.0