apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  version: "1.0.0"
  workloads:
    - name: podtato-head-hat
      version: 0.1.0
    - name: podtato-head-frontend
      version: 0.1.0
    - name: podtato-head-left-arm
      version: 0.1.0
    - name: podtato-head-right-arm
      version: 0.1.0
    - name: podtato-head-left-leg
      version: 0.1.0
    - name: podtato-head-right-leg
      version: 0.1.0
---
apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: post-deployment-loadtests
  namespace: podtato-kubectl
spec:
  container:
    name: loadtest
    image: docker.io/bacherfl/load-generator-a9e58517073467f96d2957f7b12fcc26@sha256:fd58cd2cb6528cf42f4cefebd8cadedb83ae907cd2f659733bc1729b154e83b6
    env:
      - name: URL
        value: http://podtato-head-frontend:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-frontend
  namespace: podtato-kubectl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-frontend
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        keptn.sh/post-deployment-tasks: "post-deployment-loadtests"
    spec:
      containers:
      - name: podtato-head-frontend
        image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PODTATO_COMPONENT
            value: "frontend"
          - name: SERVICES_CONFIG_FILE_PATH
            value: /config/servicesConfig.yaml
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        volumeMounts:
          - name: service-discovery-map
            mountPath: /config
      volumes:
        - name: service-discovery-map
          configMap:
            name: podtato-head-discovery

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-hat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-hat
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: podtato-head-hat
          image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PODTATO_COMPONENT
              value: "hat"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-left-leg
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-left-leg
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: podtato-head-left-leg
          image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PODTATO_COMPONENT
              value: "left-leg"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-right-leg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-right-leg
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: podtato-head-left-leg
          image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PODTATO_COMPONENT
              value: "left-leg"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-left-arm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-left-arm
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: podtato-head-left-arm
          image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PODTATO_COMPONENT
              value: "left-arm"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-right-arm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-right-arm
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: podtato-head-right-arm
          image: ghcr.io/podtato-head/podtato-server:v0.3.1 #x-release-please-version
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PODTATO_COMPONENT
              value: "right-arm"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-frontend
  namespace: podtato-kubectl
spec:
  selector:
    app.kubernetes.io/name: podtato-head-frontend
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: ClusterIP
  
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  selector:
    app.kubernetes.io/name: podtato-head-left-leg
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  selector:
    app.kubernetes.io/name: podtato-head-right-leg
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  selector:
    app.kubernetes.io/name: podtato-head-left-arm
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  selector:
    app.kubernetes.io/name: podtato-head-right-arm
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
    selector:
      app.kubernetes.io/name: podtato-head-hat
    ports:
      - name: http
        port: 8080
        protocol: TCP
    type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podtato-head-discovery
  namespace: podtato-kubectl
data:
  servicesConfig.yaml: |
    hat:       "http://podtato-head-hat:8080"
    left-leg:  "http://podtato-head-left-leg:8080"
    left-arm:  "http://podtato-head-left-arm:8080"
    right-leg: "http://podtato-head-right-leg:8080"
    right-arm: "http://podtato-head-right-arm:8080"
