apiVersion: metrics.keptn.sh/v1beta1
kind: Analysis
metadata:
  name: service-analysis
  namespace: simple-go
spec:
  timeframe:
    recent: 10m
  args:
    "workload": "simple-go-service"
  analysisDefinition:
    name: my-analysis-definition
